VERSES = [
    {"ref": "John 3:16", "text": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."},
    {"ref": "Psalm 23:1", "text": "The LORD is my shepherd; I shall not want."},
    {"ref": "Philippians 4:13", "text": "I can do all things through Christ which strengtheneth me."},
    {"ref": "Joshua 1:9", "text": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."},
    {"ref": "Romans 8:28", "text": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose."},
    {"ref": "Proverbs 3:5-6", "text": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths."},
    {"ref": "Isaiah 41:10", "text": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee."},
    {"ref": "Psalm 46:1", "text": "God is our refuge and strength, a very present help in trouble."},
    {"ref": "Matthew 11:28", "text": "Come unto me, all ye that labour and are heavy laden, and I will give you rest."},
    {"ref": "Jeremiah 29:11", "text": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."},
    {"ref": "Psalm 119:105", "text": "Thy word is a lamp unto my feet, and a light unto my path."},
    {"ref": "2 Corinthians 5:17", "text": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."},
    {"ref": "Galatians 5:22-23", "text": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance: against such there is no law."},
    {"ref": "Psalm 34:18", "text": "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit."},
    {"ref": "1 John 4:19", "text": "We love him, because he first loved us."},
    {"ref": "Romans 12:2", "text": "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God."},
    {"ref": "Psalm 27:1", "text": "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?"},
    {"ref": "Matthew 6:33", "text": "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."},
    {"ref": "Deuteronomy 31:6", "text": "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee."},
    {"ref": "Psalm 118:24", "text": "This is the day which the LORD hath made; we will rejoice and be glad in it."},
    {"ref": "1 Peter 5:7", "text": "Casting all your care upon him; for he careth for you."},
    {"ref": "Colossians 3:23", "text": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men."},
    {"ref": "Psalm 100:5", "text": "For the LORD is good; his mercy is everlasting; and his truth endureth to all generations."},
    {"ref": "James 1:2-3", "text": "My brethren, count it all joy when ye fall into divers temptations; knowing this, that the trying of your faith worketh patience."},
    {"ref": "Nehemiah 8:10", "text": "The joy of the LORD is your strength."},
    {"ref": "Psalm 37:4", "text": "Delight thyself also in the LORD: and he shall give thee the desires of thine heart."},
    {"ref": "Isaiah 40:31", "text": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."},
    {"ref": "Romans 15:13", "text": "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost."},
    {"ref": "Psalm 121:1-2", "text": "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth."},
    {"ref": "Ephesians 2:8-9", "text": "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast."},
]
